# Generated by Django 5.1.7 on 2025-06-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='The user who triggered the notification (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(help_text='Notification message content', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('member_assigned', 'Member Assigned'), ('plan_expiring', 'Plan Expiring'), ('chat', 'Chat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_community_room',
            field=models.ForeignKey(blank=True, help_text='Related community chat room, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.communitychatroom'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_room',
            field=models.ForeignKey(blank=True, help_text='Related chat room, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chatroom'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='The user who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
