# Generated by Django 5.1.7 on 2025-09-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_message_file_name_message_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for file management', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_url',
            field=models.URLField(blank=True, help_text='Cloudinary file URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True),
        ),
    ]
