# Generated by Django 5.1.7 on 2025-05-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dietplan_is_active_alter_memberattendance_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultdietplan',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='defaultdietplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='default_plan',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='default_diet_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_diet_plans', to='api.defaultdietplan'),
        ),
        migrations.AlterField(
            model_name='defaultdietplan',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('general_fitness', 'General Fitness')], max_length=15, unique=True),
        ),
    ]
