# Generated by Django 5.1.7 on 2025-05-05 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_defaultdietplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultdietplan',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AssignedDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.dietplan')),
                ('member', models.ForeignKey(limit_choices_to={'user_type': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_diets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('member', 'is_active'), name='unique_active_diet_per_member')],
            },
        ),
    ]
