# Generated by Django 5.1.7 on 2025-07-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_trainerattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
