# Generated by Django 5.1.7 on 2025-07-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_membership_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_profiles/'),
        ),
    ]
