# Generated by Django 5.1.7 on 2025-05-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_chat_room_communitychatroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_must_belong_to_chat_or_community',
        ),
        migrations.AddField(
            model_name='communitychatroom',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'member'}, related_name='community_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitychatroom',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitychatroom',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
