# Generated by Django 5.1.7 on 2025-06-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='community_chat_room',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_room_type',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('community', 'Community')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
