# Generated by Django 5.1.7 on 2025-06-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_notification_community_chat_room_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
