# Generated by Django 5.1.7 on 2025-07-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_notification_receiver_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
