# Generated by Django 5.1.7 on 2025-04-29 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
