# Generated by Django 5.1.7 on 2025-04-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_assigned_trainer_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
