# Generated by Django 5.1.7 on 2025-05-06 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_defaultdietplan_is_default_assigneddiet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWorkoutCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='workoutroutine',
            options={'ordering': ['day_number']},
        ),
        migrations.AddField(
            model_name='workoutroutine',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='workoutroutine',
            constraint=models.UniqueConstraint(fields=('member', 'day_number'), name='unique_workout_per_day_per_member'),
        ),
        migrations.AddField(
            model_name='weeklyworkoutcycle',
            name='member',
            field=models.ForeignKey(limit_choices_to={'user_type': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_workout_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='weeklyworkoutcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('member', 'is_active'), name='unique_active_cycle_per_member'),
        ),
    ]
