# Generated by Django 5.1.7 on 2025-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_weeklyworkoutcycle_alter_workoutroutine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
