# Generated by Django 5.1.7 on 2025-07-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_membershiphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
