# Generated by Django 5.1.7 on 2025-08-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_has_upgraded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiphistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Membership History', 'verbose_name_plural': 'Membership Histories'},
        ),
        migrations.RemoveField(
            model_name='membershiphistory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membershiphistory',
            name='membership_plan',
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='is_upgrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.membershipplan'),
        ),
        migrations.AddField(
            model_name='membershiphistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
