# Generated by Django 5.1.7 on 2025-08-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_membershiphistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiphistory',
            old_name='plan',
            new_name='membership_plan',
        ),
    ]
