# Generated by Django 5.1.7 on 2025-09-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_plan_membershiphistory_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
