# Generated by Django 5.1.7 on 2025-09-20 14:43

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_membershiphistory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief description about the trainer', null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='profile_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
